stages:
  ParamsToMetrics:
    cmd: zntrack run zntrack.examples.ParamsToMetrics --name ParamsToMetrics
    metrics:
    - nodes/ParamsToMetrics/metrics.json:
        cache: false
    - nodes/ParamsToMetrics/node-meta.json:
        cache: false
    params:
    - ParamsToMetrics
