plots:
- plots_WritePlots_plots:
    x:
      nodes/plots/WritePlots/plots.csv: x
    y:
      nodes/plots/WritePlots/plots.csv: y
- plots_WritePlots_1_plots:
    x:
      nodes/plots/WritePlots_1/plots.csv: x
    y:
      nodes/plots/WritePlots_1/plots.csv: y
stages:
  ParamsToMetrics:
    cmd: zntrack run zntrack.examples.nodes.ParamsToMetrics --name ParamsToMetrics
    metrics:
    - nodes/ParamsToMetrics/metrics.json
    - nodes/ParamsToMetrics/node-meta.json:
        cache: true
    params:
    - ParamsToMetrics
  outs_NumericOuts:
    cmd: zntrack run zntrack.examples.nodes.ParamsToOuts --name outs_NumericOuts
    metrics:
    - nodes/outs/NumericOuts/node-meta.json:
        cache: true
    outs:
    - nodes/outs/NumericOuts/outs.json
    params:
    - outs_NumericOuts
  outs_StringOuts:
    cmd: zntrack run zntrack.examples.nodes.ParamsToOuts --name outs_StringOuts
    metrics:
    - nodes/outs/StringOuts/node-meta.json:
        cache: true
    outs:
    - nodes/outs/StringOuts/outs.json
    params:
    - outs_StringOuts
  plots_WritePlots:
    cmd: zntrack run zntrack.examples.nodes.WritePlots --name plots_WritePlots
    metrics:
    - nodes/plots/WritePlots/node-meta.json:
        cache: true
    outs:
    - nodes/plots/WritePlots/plots.csv
    params:
    - plots_WritePlots
  plots_WritePlots_1:
    cmd: zntrack run zntrack.examples.nodes.WritePlots --name plots_WritePlots_1
    metrics:
    - nodes/plots/WritePlots_1/node-meta.json:
        cache: true
    outs:
    - nodes/plots/WritePlots_1/plots.csv
    params:
    - plots_WritePlots_1
